// <auto-generated />
using System;
using APIBanca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIBanca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515223701_AddNombreCuentaOrigenExternaToTransferencias")]
    partial class AddNombreCuentaOrigenExternaToTransferencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIBanca.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_abono");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAbono"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdCredito")
                        .HasColumnType("integer")
                        .HasColumnName("id_credito");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal>("SaldoAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_anterior");

                    b.Property<decimal>("SaldoNuevo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_nuevo");

                    b.Property<string>("TipoAbono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_abono");

                    b.HasKey("IdAbono");

                    b.HasIndex("IdCredito");

                    b.ToTable("abonos");
                });

            modelBuilder.Entity("APIBanca.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dpi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dpi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("APIBanca.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCredito"));

                    b.Property<decimal>("CuotaMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cuota_mensual");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.Property<decimal>("MontoOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_original");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_pendiente");

                    b.Property<decimal>("TasaInteres")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tasa_interes");

                    b.HasKey("IdCredito");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("creditos");
                });

            modelBuilder.Entity("APIBanca.Models.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuenta"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("SwiftBanco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("swift_banco");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdCuenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique();

                    b.ToTable("cuentas");
                });

            modelBuilder.Entity("APIBanca.Models.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<decimal>("SaldoResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_resultante");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdCuenta");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("APIBanca.Models.SolicitudCredito", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("MontoSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_solicitado");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_meses");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdCliente");

                    b.ToTable("solicitudes_credito");
                });

            modelBuilder.Entity("APIBanca.Models.Transferencia", b =>
                {
                    b.Property<int>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transferencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransferencia"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CuentaDestinoExterna")
                        .HasColumnType("text")
                        .HasColumnName("cuenta_destino_externa");

                    b.Property<int?>("CuentaDestinoId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_destino_id");

                    b.Property<string>("CuentaOrigenExterna")
                        .HasColumnType("text")
                        .HasColumnName("cuenta_origen_externa");

                    b.Property<int?>("CuentaOrigenId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_origen_id");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NombreCuentaOrigenExterna")
                        .HasColumnType("text")
                        .HasColumnName("nombre_cuenta_origen_externa");

                    b.Property<string>("SwiftDestino")
                        .HasColumnType("text")
                        .HasColumnName("swift_destino");

                    b.Property<string>("SwiftOrigen")
                        .HasColumnType("text")
                        .HasColumnName("swift_origen");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdTransferencia");

                    b.HasIndex("CuentaDestinoId");

                    b.HasIndex("CuentaOrigenId");

                    b.ToTable("transferencias");
                });

            modelBuilder.Entity("APIBanca.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("APIBanca.Models.Abono", b =>
                {
                    b.HasOne("APIBanca.Models.Credito", "Credito")
                        .WithMany("Abonos")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("APIBanca.Models.Credito", b =>
                {
                    b.HasOne("APIBanca.Models.Cuenta", "Cuenta")
                        .WithMany("Creditos")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIBanca.Models.SolicitudCredito", "SolicitudCredito")
                        .WithOne("Credito")
                        .HasForeignKey("APIBanca.Models.Credito", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("SolicitudCredito");
                });

            modelBuilder.Entity("APIBanca.Models.Cuenta", b =>
                {
                    b.HasOne("APIBanca.Models.Cliente", "Cliente")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("APIBanca.Models.Movimiento", b =>
                {
                    b.HasOne("APIBanca.Models.Cuenta", "Cuenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("APIBanca.Models.SolicitudCredito", b =>
                {
                    b.HasOne("APIBanca.Models.Cliente", "Cliente")
                        .WithMany("SolicitudesCredito")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("APIBanca.Models.Transferencia", b =>
                {
                    b.HasOne("APIBanca.Models.Cuenta", "CuentaDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("CuentaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("APIBanca.Models.Cuenta", "CuentaOrigen")
                        .WithMany("TransferenciasOrigen")
                        .HasForeignKey("CuentaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CuentaDestino");

                    b.Navigation("CuentaOrigen");
                });

            modelBuilder.Entity("APIBanca.Models.Usuario", b =>
                {
                    b.HasOne("APIBanca.Models.Cliente", "Cliente")
                        .WithOne("Usuario")
                        .HasForeignKey("APIBanca.Models.Usuario", "IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("APIBanca.Models.Cliente", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("SolicitudesCredito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APIBanca.Models.Credito", b =>
                {
                    b.Navigation("Abonos");
                });

            modelBuilder.Entity("APIBanca.Models.Cuenta", b =>
                {
                    b.Navigation("Creditos");

                    b.Navigation("Movimientos");

                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigen");
                });

            modelBuilder.Entity("APIBanca.Models.SolicitudCredito", b =>
                {
                    b.Navigation("Credito");
                });
#pragma warning restore 612, 618
        }
    }
}
